# Generated by Django 5.0.3 on 2024-10-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='mastodon_url',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='Youtube URL'),
        ),
    ]
